---
email:
  from: no-reply@company.com
  to: stakeholder@example.com
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: your-real-email@gmail.com
  password: your-app-password

tavily:
  api_key: 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
  search_max_results: 20  
scraper:
  mock_data: false
  targets:
    - name: zhaopin
      url: https://www.zhaopin.com
      enabled: true
    - name: fiftyonejob
      url: https://www.51job.com
      enabled: true
    - name: liepin
      url: https://www.liepin.com
      enabled: true
    - name: lagou
      url: https://www.lagou.com
      enabled: true
    - name: indeed
      url: https://www.indeed.com
      enabled: true
    - name: linkedin
      url: https://www.linkedin.com/jobs
      enabled: true

session_management: true
weighted_scoring: true
trust_this_host: true