#!/usr/bin/env python3
"""
Email Sender Module
Sends job recruitment reports via email
"""

import logging
import smtplib
import yaml
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from typing import List, Dict, Optional
from datetime import datetime
import os

logger = logging.getLogger(__name__)


class EmailSender:
    """Email sender for job reports"""
    
    def __init__(self, config_path: str = "config.yaml"):
        """Initialize email sender with configuration"""
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)
        
        email_config = self.config.get('email', {})
        
        self.smtp_server = email_config.get('smtp_server', 'smtp.gmail.com')
        self.smtp_port = email_config.get('smtp_port', 587)
        self.username = email_config.get('username', '')
        self.password = email_config.get('password', '')
        self.from_email = email_config.get('from', self.username)
        self.to_email = email_config.get('to', '')
        
        self._validate_config()
    
    def _validate_config(self):
        """Validate email configuration"""
        if not self.username or not self.password:
            raise ValueError("Email username and password are required")
        if not self.to_email:
            raise ValueError("Recipient email (to) is required")
        
        logger.info(f"Email configured: {self.from_email} -> {self.to_email}")
    
    def _create_html_content(self, jobs: List[Dict]) -> str:
        """Convert jobs to HTML email content"""
        html = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #2c3e50; }
                h2 { color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 5px; }
                table { border-collapse: collapse; width: 100%; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #3498db; color: white; }
                tr:nth-child(even) { background-color: #f2f2f2; }
                tr:hover { background-color: #e8f4f8; }
                .summary { background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0; }
                .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 12px; }
            </style>
        </head>
        <body>
            <h1>📋 Monthly Job Recruitment Report</h1>
            <div class="summary">
                <strong>Report Date:</strong> {date}<br>
                <strong>Total Jobs Found:</strong> {total}<br>
                <strong>Sources:</strong> {sources}
            </div>
            
            <h2>Job Listings</h2>
            <table>
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Company</th>
                        <th>Location</th>
                        <th>Source</th>
                        <th>Salary</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
        """.format(
            date=datetime.now().strftime('%Y-%m-%d'),
            total=len(jobs),
            sources=', '.join(set(j.get('source', 'Unknown') for j in jobs))
        )
        
        for job in jobs:
            title = job.get('title', 'N/A')
            company = job.get('company', 'N/A')
            location = job.get('location', 'N/A')
            source = job.get('source', 'N/A')
            salary = job.get('salary', 'N/A')
            url = job.get('url', '#')
            
            html += f"""
                    <tr>
                        <td><strong>{title}</strong></td>
                        <td>{company}</td>
                        <td>{location}</td>
                        <td>{source}</td>
                        <td>{salary}</td>
                        <td><a href="{url}">View</a></td>
                    </tr>
            """
        
        html += """
                </tbody>
            </table>
            
            <div class="footer">
                <p>This is an automated report generated by Monthly Job Monitor.</p>
                <p>Generated at: {timestamp}</p>
            </div>
        </body>
        </html>
        """.format(timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        
        return html
    
    def _create_text_content(self, jobs: List[Dict]) -> str:
        """Convert jobs to plain text email content"""
        lines = [
            "MONTHLY JOB RECRUITMENT REPORT",
            "=" * 50,
            f"Date: {datetime.now().strftime('%Y-%m-%d')}",
            f"Total Jobs: {len(jobs)}",
            "",
            "JOB LISTINGS",
            "-" * 50,
        ]
        
        for i, job in enumerate(jobs, 1):
            lines.append(f"\n{i}. {job.get('title', 'N/A')}")
            lines.append(f"   Company: {job.get('company', 'N/A')}")
            lines.append(f"   Location: {job.get('location', 'N/A')}")
            lines.append(f"   Source: {job.get('source', 'N/A')}")
            lines.append(f"   Salary: {job.get('salary', 'N/A')}")
            if job.get('url'):
                lines.append(f"   URL: {job.get('url')}")
        
        lines.append("\n" + "=" * 50)
        lines.append("Generated by Monthly Job Monitor")
        
        return "\n".join(lines)
    
    def send_report(self, jobs: List[Dict], subject: str = None) -> bool:
        """Send job report email"""
        if subject is None:
            subject = f"Monthly Job Report - {datetime.now().strftime('%Y-%m')}"
        
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = self.from_email
        msg['To'] = self.to_email
        
        # Attach plain text and HTML versions
        text_content = self._create_text_content(jobs)
        html_content = self._create_html_content(jobs)
        
        msg.attach(MIMEText(text_content, 'plain'))
        msg.attach(MIMEText(html_content, 'html'))
        
        try:
            logger.info(f"Sending email to {self.to_email}")
            
            # Connect to SMTP server and send
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)
            
            logger.info("Email sent successfully!")
            return True
            
        except smtplib.SMTPException as e:
            logger.error(f"SMTP Error: {e}")
            return False
        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False
    
    def send_report_with_attachment(self, jobs: List[Dict], 
                                     attachment_path: str,
                                     subject: str = None) -> bool:
        """Send report with file attachment"""
        if subject is None:
            subject = f"Monthly Job Report - {datetime.now().strftime('%Y-%m')}"
        
        msg = MIMEMultipart('mixed')
        msg['Subject'] = subject
        msg['From'] = self.from_email
        msg['To'] = self.to_email
        
        # Create body
        body = MIMEText(self._create_text_content(jobs), 'plain')
        msg.attach(body)
        
        # Attach file
        with open(attachment_path, 'rb') as f:
            part = MIMEApplication(f.read())
            part.add_header('Content-Disposition', 'attachment', 
                          filename=os.path.basename(attachment_path))
            msg.attach(part)
        
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)
            
            logger.info("Email with attachment sent successfully!")
            return True
            
        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False


def main():
    """Test email functionality"""
    logging.basicConfig(level=logging.INFO)
    
    # Test with sample data
    sample_jobs = [
        {
            'title': 'Software Engineer',
            'company': 'Google',
            'location': 'Mountain View, CA',
            'source': 'LinkedIn',
            'salary': '$150,000 - $200,000',
            'url': 'https://careers.google.com'
        },
        {
            'title': 'Data Scientist',
            'company': 'Microsoft',
            'location': 'Seattle, WA',
            'source': 'Indeed',
            'salary': '$120,000 - $160,000',
            'url': 'https://careers.microsoft.com'
        }
    ]
    
    sender = EmailSender()
    # Note: This will actually try to send an email
    # Uncomment to test:
    # sender.send_report(sample_jobs)


if __name__ == '__main__':
    main()